node.id=5
process.roles=broker
controller.quorum.voters=1@broker1:29093,2@broker2:29093,3@broker3:29093
controller.listener.names=CONTROLLER
listeners=PLAINTEXT://:9092
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
inter.broker.listener.name=PLAINTEXT
log.dirs=/var/lib/kafka/data

# Cruise Control Metrics Reporter
metric.reporters=com.linkedin.kafka.cruisecontrol.metricsreporter.CruiseControlMetricsReporter
cruise.control.metrics.reporter.bootstrap.servers=broker1:9092,broker2:9092,broker3:9092,broker4:9092,broker5:9092,broker6:9092
cruise.control.metrics.reporter.metrics.topic=__CruiseControlMetrics
