bootstrap.servers=broker1:9092,broker2:9092,broker3:9092,broker4:9092,broker5:9092,broker6:9092

# KRaft kullanıyorsun, ZK yok → bunun yerine broker failure detection aç
kafka.broker.failure.detection.enable=true

sample.store.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.KafkaSampleStore
capacity.config.file=config/capacityJBOD.json
metric.sampler.class=com.linkedin.kafka.cruisecontrol.monitor.sampling.CruiseControlMetricsReporterSampler

webserver.http.port=9090


# Cruise Control gerekli topicleri otomatik oluşturabilsin
create.topic.enable=true

# Metric sample topic isimleri
partition.metric.sample.store.topic=__CruiseControlPartitionMetricSamples
broker.metric.sample.store.topic=__CruiseControlBrokerMetricSamples

partition.metric.sample.store.topic.replication.factor=3
broker.metric.sample.store.topic.replication.factor=3

webserver.http.address=0.0.0.0
webserver.http.port=9090

# Minimum window sayısını azalt (test için)
num.partition.metrics.windows=1
num.broker.metrics.windows=1
min.valid.partition.ratio=0.5